# Generated by Django 6.0.2 on 2026-03-15 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorías', '0001_initial'),
        ('tareas', '0002_alter_tarea_fecha_fin_alter_tarea_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='categorías.categoria'),
        ),
    ]
