# Generated by Django 6.0.2 on 2026-03-15 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorías', '0004_alter_categoria_usuario'),
        ('tareas', '0004_alter_tarea_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='categorías.categoria'),
        ),
    ]
