# Generated by Django 6.0.2 on 2026-04-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_alter_tarea_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='resumen_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='subtareas_ia',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
