# Generated by Django 6.0.2 on 2026-04-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_tarea_resumen_ia_tarea_subtareas_ia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='resumen_ia',
        ),
    ]
